### ISSUE TITLE
Is the inertia calculation for the 3D Link correct?

### ISSUE THREAD

**Issue by zicodasilva** [alknemeyer/physical_education#3]
It probably is, but thought to open an issue just in case :)
```python
I_len = (self.mass_sym * self.radius_sym**2)/2
I_wid = (self.mass_sym * self.length_sym**2)/12
if aligned_along.endswith('x'):
    self.inertia = sp.diag(I_len, I_wid, I_wid)
    offset_b = Mat([-self.length_sym/2, 0, 0])
elif aligned_along.endswith('y'):
    self.inertia = sp.diag(I_wid, I_len, I_wid)
    offset_b = Mat([0, -self.length_sym/2, 0])
else:
    self.inertia = sp.diag(I_wid, I_wid, I_len)
    offset_b = Mat([0, 0, -self.length_sym/2])
```
The above code is responsible for calculating the inertia of a 3D link that is modelled as a rigid cylinder. I haven't done extensive research and don't have any experience with inertia, but the following [link](https://study.com/skill/learn/how-to-calculate-the-moment-of-inertia-for-a-cylinder-explanation.html) suggests that the inertia should be calculated as (aligned with the z-axis):
```
I_z = (1/2)*m*r^2
I_x = I_y = (1/4)*m*r^2 + (1/12)*L^2
```
However, this doesn't match the above? The axis aligned calculation is the same but not the others. Can you explain the above?

**Comment by zicodasilva** [comment]
@alknemeyer Amir seems to think that you modelled the inertia for the perpendicular axis as an "infinitely thin rod" i.e. r -> 0. This would make `I_x` and `I_y` `(1/12)*L^2` for a z-axis aligned rod. For reference: https://www.physicsforums.com/threads/question-about-the-inertia-matrix-of-a-bar.909598/. Does this sound familiar? Then I think we would need to set the inertia for the aligned axis to `0` and not model links as cylinders and rather thin rods?

**Comment by alknemeyer** [comment]
That rings a bell actually! I imagine I got mixed up with infinitely thin rod vs cylinder

**Comment by zicodasilva** [comment]
Yes, that does seem to be the case. I suppose having the cylinder modelled, we could model a thin rod by using `r=0`. Probably something to note if a simpler model is wanted.

In any case, this issue has been resolved now. Thanks.
