### ISSUE TITLE
Saving system to file without pyomo objects

### ISSUE THREAD

**Issue by zicodasilva** [alknemeyer/physical_education#4]
I've noticed that there is a `system.save_data_to_file` method which is great to save an existing model of the system. However, it seems to only include the model after transcription i.e. converted to pyomo objects. I think this is how it works?

Would it be better to have a `system.save_model_to_file` method which saves the symbolic model of the system i.e. the equations of motion (EOM lambdified) along with the links of the system. This way, one can develop a model and setup different trajectory optimisation problems without having to redo the EOM (in case of loss of data/ shutdown of python) or be locked into a particular trajectory.

If this sort of functionality exists, let me know.

**Comment by alknemeyer** [comment]
Hey Zico. I actually have a notebook which I now realise isn't in this repo. I'll neaten it up a bit and then share it, because it may answer some common usage questions. You're right that `save_data_to_file` doesn't save the model, but you can actually do that using just `dill`:
```python
# Make your model
robot, add_pyomo_constraints = pe.models.quadruped3D.model(
	pe.models.quadruped3D.parameters['mean-male']
)
robot.calc_eom(simp_func=lambda x: pe.utils.parsimp(x, nprocs=12)

# Then, eventually, save the symbolic model
outfilename = './cheetah-with-tail-no-drag-choose-a-detailed-name'  # Or describe the metadata somewhere else
with open(f'{outfilename}_tmp.robot', 'wb') as f:
    # Save the `add_pyomo_constraints` function, because it must correspond to the
    # model and you may change the source in between saving and loading. A potential
    # source of bugs
	dill.dump([robot, add_pyomo_constraints], f)

# Load and test it
with open(f'{robotname}_tmp.robot', 'rb') as f:
    robot2, add_pyomo_constraints2 = dill.load(f)
# ~ ~ ~ run your optimisation ~ ~ ~

# If it looks good, rename. (Most likely, overwrite an existing model)
import os
os.rename(f'{robotname}_tmp.robot', f'{robotname}.robot')
```

**Comment by alknemeyer** [comment]
For an example of the function you found, I used this snippet:
```python
description = (f'{velocity} m/s periodic gallop, foot order = {foot_order_vals}\n'
               f'for feet = {[foot.name for foot in feet]}.\n'
               f'Final penalty cost: {pyomo.environ.value(costs["penalty"])}\n'
               f'status = {ret.Solver.status}, message = {ret.Solver.Message}\n'
               f'solve time = {ret.Solver.Time:.1f} seconds\n'
               f'gallop time = {total_time}\n'
               f'The code in the init function:\n{inspect.getsource(setup_fn)}\n'
               f'The code in the solver schedule function:\n{inspect.getsource(solver_fn)}')
filename = f'robots-and-data/{model}-i={loop}-v={velocity}-t={t}-o={o}-time={total_time}.data'
print('saving with filename =', filename)
robot.save_data_to_file(filename, description, overwrite_existing=True)
```
The details aren't so important but you get the idea. It helped quite a bit when looking at old data, but something like a Git commit branch could nicely sum up everything too. `inspect.getsource(<function>)` is awesome if put all your setup into `<function>` and are feeling too lazy to properly describe it. All of this is only really useful if you're comparing many variations

**Comment by zicodasilva** [comment]
Thanks for the examples. Yes, I realised that it is pretty simple to `dill` it and go from there. I will close this issue because I don't think it will be worth it to add a method in `System` to do this, and an examples file with this information should be enough :)
