### ISSUE TITLE
Clarity on the `Foot3D` class and general GRF stuff

### ISSUE THREAD

**Issue by zicodasilva** [alknemeyer/physical_education#6]
Can you clarify a few things for me? First of all, what units do you assume the GRF data to be:
```python
GRFxy = Var(m.fe, m.cp, fric_set, name='GRFxy', bounds=(0, self.GRFxy_max))
GRFz = Var(m.fe, m.cp, name='GRFz', bounds=(0, self.GRFz_max))
```
? I have some GRF data in Newtons (and depending on the direction of the force it can be negative) so maybe you assume magnitude here? My GRF data looks like this:
![Arabia_070909_06](https://user-images.githubusercontent.com/8395831/159341106-301ff0bc-80a0-4e8a-b80f-9c84815e5989.png)
Just to make sure I'm understanding things correctly, do the following sympy variables (`Lx` and `Lz`) correspond to the above pyomo variables:
```python
self.Lx = Mat(sp.symbols('L_{%s/x:%s}' % (name, nsides)))
self.Lz = sp.Symbol('L_{%s/z}' % name)
self.L = Mat(self.D).T @ self.Lx + Mat([0, 0, self.Lz])  # type: ignore
```
And the EOM for the contacts is standard the standard contact jacobian J^T.λ:
```python
def calc_eom(self, q: Mat, dq: Mat, ddq: Mat) -> Mat:
    self.Pb_I_vel = self.Pb_I.jacobian(q) @ dq
    jac_L = self.Pb_I.jacobian(q)
    return jac_L.T @ self.L
```
In assuming the above, I have tried to add GRF data as a "parameter" into the optimisation (so no estimation of the contacts, and instead just use the data as is into the contact model):
```python
    Fz = signal.resample_poly(grf["Fz"].values, up=2, down=7, axis=0)[::downsample_factor]
    Fx = signal.resample_poly(grf["Fx"].values, up=2, down=7, axis=0)[::downsample_factor]
    Fy = signal.resample_poly(grf["Fy"].values, up=2, down=7, axis=0)[::downsample_factor]
    for foot in foot_contact_order.keys():
        for contact_seq in foot_contact_order[foot]:
            contact_seq[0] //= downsample_factor
            contact_seq[1] //= downsample_factor
    for foot in pe.foot.feet(robot):
        grfz = foot["GRFz"]
        grfxy = foot["GRFxy"]
        foot_height = foot["foot_height"]
        foot_on_ground_indices = []
        try:
            for contact_seq in foot_contact_order[foot.name]:
                foot_on_ground_indices = foot_on_ground_indices + list(range(contact_seq[0], contact_seq[1]))
        except KeyError:
            pass
        for fe, cp in robot.indices(one_based=True):
            grfz[fe, cp].fix(Fz[start_frame + fe - 1])
            # grfz[fe, cp].value = Fz[start_frame + fe - 1]
            if fe - 1 in foot_on_ground_indices:
                foot_height[fe, cp].fix(0)
            # Note, range(4) corresponds with the friction polygon estimate using 4 sides. There is also an option to use 8 sides.
            for i in range(4):
                grfxy[fe, cp, i].fix(foot.D[i, 0] * Fx[start_frame + fe - 1] + foot.D[i, 1] * Fy[start_frame + fe - 1])
                # grfxy[fe, cp, i].value = foot.D[i, 0] * Fx[start_frame + fe - 1] + foot.D[i, 1] * Fy[start_frame + fe - 1]
```
Do you see anything completely wrong here (mis-understanding or something)?

**Comment by alknemeyer** [comment]
Hi, sorry for the delay! I just partially answered this in issue #7. GRF has units in Newtons, but scaled by `force_scale`. `Lx` corresponds to `GRFxy`, and `Lz` corresponds to `GRFz` (I wanted to stick to the usual naming schemes I found in papers but apparently abandoned that in pyomo)

`GRFz` is simple (it's just a normal force value) but `GRFxy` is... complicated (at least, in 3D). It took me quite a while to understand why the friction polygon math works out. Amir has the papers for that but we could maybe go through the equations together if you want. Anyway, each component of the friction polygon is a positive vector. You positive/negative Fx and Fy values would have to be put into the right component of the polygon. I'm a bit rusty on this stuff so I can't comment on your code, but I'll have a look this weekend.

**Comment by zicodasilva** [comment]
@alknemeyer Thanks for clarifying things. I really appreciate the time you taking out to answer my questions. If you available for chat about this, let me know!

**Comment by zicodasilva** [comment]
@alknemeyer I'm not 100% comfortable with the contact stuff so a catch up would be good, if you are willing to provide your time for it :) I read the `An Implicit Time-Stepping Scheme for Rigid Body Dynamics with Coulomb Friction` paper that Amir shared with me, a bit over my head, but I have a high level understanding of things. Based on that and what you said about "each component of the friction polygon is a positive vector", I decided that I could project the tangential GRF into each component if it has a positive magnitude in that direction i.e.
```python
for i in range(foot.nsides):
    # Project force data onto each component of the polygon friction.
    force_comp = np.array([x_comp, y_comp, 0]).dot(foot.D[i, :])
    if force_comp >= 0:
        # There is a force component in the direction foot.D.
        grfxy[fe, cp, i].value = force_comp
```
what you think?

**Comment by alknemeyer** [comment]
Hey, so sorry for the delay again! I think that's the right idea, although I still haven't reread the paper and code.

Let's have a video chat and go through the paper together. I seem to have been kicked off the lab's Teams account. Could you send me an email at `$githubusername at hey dot com` and we can find a time?

**Comment by zicodasilva** [comment]
@alknemeyer Did you receive my email?

**Comment by zicodasilva** [comment]
Long overdue, but here is a result from projecting the horizontal GRF into a 4-sided polygon. To validate things, I just calculated the magnitude of the horizontal force when approximated by the polygon, and compared this with the magnitude from the force measurements.
![image](https://user-images.githubusercontent.com/8395831/169700584-500f54d4-0b98-450d-9f86-e8abebdcb9a4.png)
Looks like it is close enough. Would be interesting to compare with the 8-sided polygon.

With this result, I think I will close this issue :)

**Comment by alknemeyer** [comment]
Looks amazing! Thanks for letting me know. Hope your research is going well 🕵️‍♂️
