### ISSUE TITLE
Possible issue with force scales

### ISSUE THREAD

**Issue by zicodasilva** [alknemeyer/physical_education#7]
You scale forces by body weight (by default) and the following forces are scaled:
```python
self.force_scale = sp.Symbol('F_{scale}')
to_sub = {force: force*self.force_scale for force in [  # TODO: this should be done by the links themselves!
    *flatten(torque.input_torques for torque in motor.torques(self)),
    *Fr,
    *flatten(foot.Lx for foot in feet),
    *[foot.Lz for foot in feet],
]}
```
The torques are bounded as follows:
```python
Tc = Var(m.fe, Tc_set, name='Tc', bounds=self.torque_bounds)
```
For the example cheetah model you use torque bounds that are majority below `1`:
```python
"neck": {
     "torque_bounds": (-0.5, 0.5),
     "no_load_speed": 50.
},
```
Do you scale this bound by body weight? Otherwise, it would be very small? Same goes for the GRF. For the cheetah model you have bounds of around `5` but the ground reaction force data that I have can go up to around 1000N.

**Comment by zicodasilva** [comment]
Actually, thinking about it, there is no need to include the scale in the bounds for the pyomo variable. The pyomo variable might be bounded between `(-0.5, 0.5)` but in actual fact this would allow for torques of `0.5*body_weight` in the EOM. Same for the GRF, so this is not an issue? I will let you close it if what I'm saying makes sense.

**Comment by alknemeyer** [comment]
Hey. Your second message is correct but I'll write out an explanation anyway: say you have `F = m * a` where `m` is a really big constant (eg `10^9`), and `a` and `F` are variables to be found by the optimiser.

If `a` is around 1, `F` would be really big too (near the value of `m`), which might cause numerical stability issues in other parts of the problem (eg some matrix would have huge disparity between the numbers it contains, resulting in slower convergence). If `F` was constrained in some other part of the problem, it might look something like `-2m < F < 2m`

Instead we write `F_scale * F_ = m * a`, where `F_scale` is a constant equal to `m` and `F_` is the variable to be found. This time `F_` will be approximately 1 (resulting in nice numerical properties for the solver). In general, everywhere where `F` is used, you'd put `F_scale * F_`. The previous constraint would now be `-2 < F_ < 2`.

Anyway, back to the library: the forces and libraries (`force` in the first code snippet you posted) are all scaled (normalized) and are equivalent to `F_` my example. Given that `force` (the variable) is normalised by `force_scale`, all the constraints on `force` are scaled by `force_scale` too. Maybe it would be a good idea to add an explanation of this to the docs.
