### ISSUE TITLE
Support for 2D systems

### ISSUE THREAD

**Issue by zicodasilva** [alknemeyer/physical_education#8]
I'm not sure at the moment the effort involved to create corresponding `System2D`, `Link2D`, `Motor2D` etc. It would be nice to support this to allow for rapid prototyping on simple toy examples. I will do a quick check to see the effort, but if you have any insights or guidance here, let me know.

I'm still keeping an eye on [DRAKE](http://drake.mit.edu/) because I think it might be perfect for more advanced systems later on. But I think this library will still be useful from a learning perspective for other students to dip their toe into trajectory optimisation, before having to become familiar with a full fledged robotics toolbox.

What you think?

**Comment by zicodasilva** [comment]
So I'm looking at implementing the bare minimum for 2D support - that would be `Link2D`, `Motor2D`, `System2D`. However, there is nothing 3D specific to `System3D` besides the plotting. I'm thinking that we have a base class `SystemBase` which both `System2D` and `System3D` inherit so that we minimise code duplication. That said the `Link2D` is also pretty similar to the `Link3D` and again plotting is the main difference (as well as the construction). Could think about a `LinkBase` too. I haven't looked at `Motor2D` yet but I'm thinking that should just be a simple torque variable about the one possible axis of rotation.

**Comment by zicodasilva** [comment]
I've created a branch: [two-dim-systems](https://github.com/alknemeyer/physical_education/tree/two-dim-systems). It has the basic 2D versions of `Link2D`, `Motor2D` and `System2D` implemented. I think it would probably be worth doing the `Foot2D` at some point. I still need to clean it up a lot because a lot of the 2D and 3D versions are the same.

I've supported fixed based for things like the acrobot. I might support "fixed rotation base" for a cart-pole system but not sure that would be worth it. The 2D versions are more for toy examples, allowing for quick development of core ideas. So maybe it is good to keep it simple and build on it as we need more functionality.

Just so you have some context, I'm looking at estimating the torques of a system provided that the kinematics are fixed. We need this for the cheetah but it is a bit complicated at the moment because we don't know what should be in the cost function. Working with a 2D acrobot (and eventually a 3D monopod) will provide some useful insights. We also need to do a robust analysis (i.e. vary the parameters, like mass, link length etc) of estimating the torques. We know that we are pretty uncertain about the cheetah model so know how robust the method is, will quickly give us an idea whether it will transfer to the cheetah model.

**Comment by alknemeyer** [comment]
Awesome, I just skimmed some of the commits and they look good! I feel bad every time I see a "fix bug" relating to code I put there :face_with_spiral_eyes: hope the library isn't being frustrating to work with

Hah, I didn't know the cost function for my entire msc too. What you're doing sounds really cool though! I don't have a real reason why I didn't add 2D versions of everything. I guess I thought it would be a lot of work, and I wasn't planning on using it myself.

It would be awesome if you could make a model in 2D, get it working, rapidly figure out the cost function/useful constraints/etc, then change a few lines and have it working in 3D (with the same/similar cost). Nice work!

**Comment by zicodasilva** [comment]
I've merged the 2D implementations to the alpha branch. I'm closing this task. Further issues can be logged as separate tasks. @alknemeyer If you are inclined to build a simple example to test things, let me know the results :)

**Comment by alknemeyer** [comment]
Awesome, will let you know if I do!
